export type Client = {
  id: string;
  brand: string;
  property: string;
  city: string;
  state: string;
  coordinates: [number, number]; // [lng, lat]
  testimonial?: { quote: string; author: string; rating: 1 | 2 | 3 | 4 | 5 };
  logoUrl?: string;
};

export const clients: Client[] = [
  {
    id: "abv-001",
    brand: "Americas Best Value Inn",
    property: "ABV Inn",
    city: "Atlanta",
    state: "GA",
    coordinates: [-84.388, 33.749],
    logoUrl: "/img/logos/Americas_Best_Value_Inn_Logo.png",
    testimonial: {
      quote:
        "Kiosist has helped us greatly with our check-in process. Our guests love the seamless experience.",
      author: "Rakesh Patel",
      rating: 5,
    },
  },
  {
    id: "hi-001",
    brand: "Holiday Inn",
    property: "Holiday Inn Express",
    city: "Dallas",
    state: "TX",
    coordinates: [-96.797, 32.776],
    logoUrl: "/img/logos/holiday-inn.svg",
  },
  {
    id: "mi-001",
    brand: "Microtel",
    property: "Microtel Inn & Suites",
    city: "Charlotte",
    state: "NC",
    coordinates: [-80.843, 35.227],
    logoUrl: "/img/logos/Microtel Logo.png",
  },
  {
    id: "la-001",
    brand: "La Quinta",
    property: "La Quinta by Wyndham",
    city: "Houston",
    state: "TX",
    coordinates: [-95.369, 29.76],
    logoUrl: "/img/logos/laquinta logo.png",
  },
  {
    id: "mo-001",
    brand: "Motel 6",
    property: "Motel 6",
    city: "Phoenix",
    state: "AZ",
    coordinates: [-112.074, 33.448],
    logoUrl: "/img/logos/Motel6 logo.png",
  },
  {
    id: "su-001",
    brand: "Super 8",
    property: "Super 8 by Wyndham",
    city: "Orlando",
    state: "FL",
    coordinates: [-81.379, 28.538],
    logoUrl: "/img/logos/Super-8-Logo.png",
  },
  {
    id: "ec-001",
    brand: "Econo Lodge",
    property: "Econo Lodge",
    city: "Nashville",
    state: "TN",
    coordinates: [-86.782, 36.162],
    logoUrl: "/img/logos/Econolodge Logo.png",
  },
  {
    id: "ro-001",
    brand: "Rodeway Inn",
    property: "Rodeway Inn & Suites",
    city: "Las Vegas",
    state: "NV",
    coordinates: [-115.137, 36.175],
    logoUrl: "/img/logos/rodeway.svg",
  },
  {
    id: "bw-001",
    brand: "Baymont",
    property: "Baymont by Wyndham",
    city: "Denver",
    state: "CO",
    coordinates: [-104.9903, 39.7392],
    logoUrl: "/img/logos/Baymont Logo.png",
  },
  {
    id: "di-001",
    brand: "Days Inn",
    property: "Days Inn by Wyndham",
    city: "Indianapolis",
    state: "IN",
    coordinates: [-86.1581, 39.7684],
    logoUrl: "/img/logos/Days Inn.png",
  },
  {
    id: "ds-001",
    brand: "Days Inn & Suites",
    property: "Days Inn & Suites by Wyndham",
    city: "Columbus",
    state: "OH",
    coordinates: [-82.9988, 39.9612],
    logoUrl: "/img/logos/gilman-logo-days-inn.png",
  },
  {
    id: "ht-001",
    brand: "HomeTowne Studios",
    property: "HomeTowne Studios by Red Roof",
    city: "Kansas City",
    state: "MO",
    coordinates: [-94.5786, 39.0997],
    logoUrl: "/img/logos/HomeTowne Studios Logo.png",
  },
  {
    id: "hj-001",
    brand: "Howard Johnson",
    property: "Howard Johnson by Wyndham",
    city: "Sacramento",
    state: "CA",
    coordinates: [-121.4944, 38.5816],
    logoUrl: "/img/logos/Howard-Johnson-logo.png",
  },
  {
    id: "qi-001",
    brand: "Quality Inn",
    property: "Quality Inn",
    city: "Chicago",
    state: "IL",
    coordinates: [-87.6298, 41.8781],
    logoUrl: "/img/logos/Quality-Inn-Icon-New-1.png",
  },
  {
    id: "rr-001",
    brand: "Red Roof Inn",
    property: "Red Roof Inn",
    city: "Cincinnati",
    state: "OH",
    coordinates: [-84.5120, 39.1031],
    logoUrl: "/img/logos/RedRoof Logo 2.png",
  },
  {
    id: "si-001",
    brand: "Sleep Inn",
    property: "Sleep Inn",
    city: "Raleigh",
    state: "NC",
    coordinates: [-78.6382, 35.7796],
    logoUrl: "/img/logos/Sleep Inn Logo.png",
  },
  {
    id: "ss-001",
    brand: "SureStay",
    property: "SureStay by Best Western",
    city: "Salt Lake City",
    state: "UT",
    coordinates: [-111.8910, 40.7608],
    logoUrl: "/img/logos/SureStay Logo1.png",
  },
  {
    id: "tl-001",
    brand: "Travelodge",
    property: "Travelodge by Wyndham",
    city: "Seattle",
    state: "WA",
    coordinates: [-122.3321, 47.6062],
    logoUrl: "/img/logos/Travelodge logo.png",
  },
];

export const brandLogos = [
  { name: "Americas Best Value Inn", logoUrl: "/img/logos/abv.svg" },
  { name: "Holiday Inn", logoUrl: "/img/logos/holiday-inn.svg" },
  { name: "Microtel", logoUrl: "/img/logos/microtel.svg" },
  { name: "La Quinta", logoUrl: "/img/logos/laquinta.svg" },
  { name: "Motel 6", logoUrl: "/img/logos/motel6.svg" },
  { name: "Super 8", logoUrl: "/img/logos/super8.svg" },
  { name: "Econo Lodge", logoUrl: "/img/logos/econolodge.svg" },
  { name: "Rodeway Inn", logoUrl: "/img/logos/rodeway.svg" },
  { name: "Days Inn", logoUrl: "/img/logos/daysinn.svg" },
  { name: "Comfort Inn", logoUrl: "/img/logos/comfort.svg" },
];
